baseurl = "https://blog.budzynskimaciej.pl"
title = "Budzyński Maciej - blog"
description = "Blog programistyczny inżyniera oprogramowania, miłośnika technologi i absolwenta informatki Macieja Budzyńskiego"
copyright = "Copyright (c) 2023, wszelkie prawa zastrzeżone."
canonifyurls = true
languageCode = "pl-PL"
paginate = 3
theme = "hugo-dusk"
enableEmoji = true
pygmentsStyle = "monokai"

googleAnalytics = "UA-89868475-2"
disqusShortname = "budzynskimaciej"

[author]
  name = "Maciej Budzynski"

SectionPagesMenu = "main"

[[menu.main]]
  name = "Posty"
  weight = -120
  identifier = "post"
  url = "/post/"

[[menu.main]]
  name = "Tagi"
  weight = -110
  identifier = "tag"
  url = "/tags/" 

[params.meta]
  keywords = "blog, tech, IT, programming, budzynski, maciej, budzynskimaciej, python, java, golang, hugo, software, engineer"
  description = "Blog programisty Maciej Budzyński"

[params]
  github = "BudzynskiMaciej"
  twitter = "BudzynskiMaciek"
  mastodon = "BudzynskiMaciej"
  linkedin = "budzynskimaciej"
  email = "kontakt@budzynskimaciej.pl"
  facebook = "maciej.budzynski1"